### ISSUE TITLE
Docker image and runpod template disappear

### ISSUE THREAD

**Issue by alexbrowngh** [ashleykleynhans/text-generation-docker#5]
The docker image and the runpod template seem to disappear.

**Comment by ashleykleynhans** [comment]
RunPod keeps banning me from their Discord server after all the work I have put into building literally dozens of templates for their platform. They have also stopped paying TheLastBen and he also removed his template from their platform. They have obviously grown too big for their boots since they received a significant round of investment, so I will no longer be supporting the RunPod platform until they change their attitude towards community members that put in so much hard work to making their platform a success.

**Comment by alexbrowngh** [comment]
I'm so sorry to hear that. Thank you for all your effort, it's much appreciated.
